# Sentdex: Neural Networks and Deep Learning 1: Introduction


What is Pytorch?    
Basically a library to help with 2D Array maths. Numpy with helpper functions, no need of building optimizers and back propagation etc. 

Problem with NumPy - Doesn't run on the GPU.

GPU - large no. of small calculations like - adjusting weights in a NN    
More cores (thousands), thus much faster.

CPU - small no. of large calcualtions



Tensor is basically a 2D array






In [1]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [2]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [3]:
x.shape


torch.Size([2, 5])

In [4]:
y = torch.rand([2,5])
print(y)

tensor([[0.6537, 0.0316, 0.9165, 0.9342, 0.8911],
        [0.9869, 0.1963, 0.5063, 0.4329, 0.5754]])


For example, an image is 64x64 pixels, you cannot insert the 64x64 matrix into the neural network , so we flatten it into a 1D (1, 4096) matrix

In [5]:
y = y.view([1,10])
print(y)  

tensor([[0.6537, 0.0316, 0.9165, 0.9342, 0.8911, 0.9869, 0.1963, 0.5063, 0.4329,
         0.5754]])
